cassandra:
  image: logimethods/docker-cassandra
  ports:
    - 7000:7000
    - 7001:7001
    - 7199:7199
    - 9042:9042
    - 9160:9160
zeppelin:
#  image: logimethods/docker-zeppelin:latest
  image: local-docker-zeppelin:experiment
  ports:
    - 8080:8080
    - 8081:8081
  volumes:
    - ./data:/zeppelin/data
    - ./notebook:/zeppelin/notebook
    - ./conf:/zeppelin/conf
    - ./libs:/zeppelin/libs
  links: 
    - cassandra

