zeppelin:
  image: logimethods/docker-zeppelin:latest
  ports:
    - 8080:8080
    - 8081:8081
  volumes:
    - ./data:/zeppelin/data
    - ./notebook:/zeppelin/notebook
    - ./conf:/zeppelin/conf
    - ./libs:/zeppelin/libs

